In [2]:
import dataGenerator
import NeuralNets as NN
import pandas as pd
import numpy as np


In [3]:
dg = dataGenerator.ParityDataGenerator()
df = dg.generate_data()
print(df)


    digit1  digit2  digit3  digit4  label
0        0       0       0       0      0
1        0       0       0       1      1
2        0       0       1       0      1
3        0       0       1       1      0
4        0       1       0       0      1
5        0       1       0       1      0
6        0       1       1       0      0
7        0       1       1       1      1
8        1       0       0       0      1
9        1       0       0       1      0
10       1       0       1       0      0
11       1       0       1       1      1
12       1       1       0       0      0
13       1       1       0       1      1
14       1       1       1       0      1
15       1       1       1       1      0


In [5]:
def get_base_model_obj():
    input = NN.InputLayer(n_neurons=4)
    hid1 = NN.DenseLayer(n_neurons=4, previous_layer=input)
    # hid1 = NN.DenseLayer(n_neurons=4, previous_layer=hid1)
    hid2 = NN.DenseLayer(n_neurons=1, previous_layer=hid1, isOutput=True)
    mdl = NN.Model(input_layer=input, output_layer=hid2)
    return mdl


In [13]:
epoch_num = []
logs = []
for lr in np.arange(0.05, 0.5, 0.05):
    mdl = get_base_model_obj()
    log = get_base_model_obj().fit(df.drop(columns=['label']).values, df['label'].values.reshape(-1,1), lr=lr, momentum=0,max_epochs=100)
    logs.append(log)
    epoch_num.append(len(log))

100%|██████████| 100/100 [00:00<00:00, 222.82it/s]


In [14]:
epoch_num = []
for i in range(len(logs)):
    epoch_num.append(len(logs[i]))
print(epoch_num)

[100, 100, 100, 100, 100, 100, 100, 100, 100]


In [10]:
df = df.sample(frac=1.0)
mdl = get_base_model_obj()
log = get_base_model_obj().fit(df.drop(columns=['label']).values, df['label'].values.reshape(-1,1), lr=0.01, momentum=0,max_epochs=1000)
# logs.append(log)

print(log[-1])

100%|██████████| 1000/1000 [00:02<00:00, 415.52it/s]


[0.5002927]


In [20]:
epoch_num = []
logs = []
mdl_=None
for lr in np.arange(0.05, 0.5, 0.05):
    mdl = get_base_model_obj()
    log = get_base_model_obj().fit(df.drop(columns=['label']).values, df['label'].values.reshape(-1,1), lr=lr, momentum=0.9,max_epochs=100)
    logs.append(log)
    print(log[len(log)-1])
    epoch_num.append(len(log))
    if lr < 0.1:
        mdl_ = mdl
print(mdl_.predict(df.drop(columns=['label']).values))
print(df['label'].values)


100%|██████████| 100/100 [00:00<00:00, 185.68it/s]

[0.49999568]
[0.50002465]
[0.50001931]
[0.49999881]
[0.49999273]
[0.50003043]
[0.49999195]
[0.50000073]
[0.49999657]
[[0.27080012]
 [0.2882364 ]
 [0.26372979]
 [0.27761821]
 [0.28963025]
 [0.30843979]
 [0.2782724 ]
 [0.29564883]
 [0.26719874]
 [0.28391063]
 [0.25979015]
 [0.27364656]
 [0.28457567]
 [0.30388702]
 [0.27381914]
 [0.29260144]]
[0 1 1 0 1 0 0 1 1 0 0 1 0 1 1 0]


In [16]:
print(epoch_num)
print(logs[0])

[100, 100, 100, 100, 100, 100, 100, 100, 100]
[array([0.49997746]), array([0.49997717]), array([0.49997691]), array([0.49997669]), array([0.49997651]), array([0.49997634]), array([0.4999762]), array([0.49997607]), array([0.49997597]), array([0.49997587]), array([0.49997578]), array([0.49997571]), array([0.49997564]), array([0.49997558]), array([0.49997553]), array([0.49997548]), array([0.49997544]), array([0.4999754]), array([0.49997536]), array([0.49997533]), array([0.4999753]), array([0.49997527]), array([0.49997525]), array([0.49997522]), array([0.4999752]), array([0.49997518]), array([0.49997516]), array([0.49997514]), array([0.49997512]), array([0.4999751]), array([0.49997509]), array([0.49997507]), array([0.49997506]), array([0.49997504]), array([0.49997503]), array([0.49997501]), array([0.499975]), array([0.49997498]), array([0.49997497]), array([0.49997496]), array([0.49997494]), array([0.49997493]), array([0.49997492]), array([0.49997491]), array([0.49997489]), array([0.499974

In [7]:
from keras.layers import Dense, Input
from keras.models import Model
from keras import optimizers
from keras import regularizers
import os

Using TensorFlow backend.
C:\Users\rolo_\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\rolo_\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\rolo_\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\rolo_\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning:

In [12]:
df = df.sample(frac=1).astype(np.float64)

input = Input([4,])
d = Dense(4,activation='sigmoid',activity_regularizer=regularizers.l1(0.01))(input)
o = Dense(1,activation='sigmoid',activity_regularizer=regularizers.l1(0.01))(d)
optimizer = optimizers.Adam(lr=1e-2)
model = Model(inputs=input,outputs=o)
model.compile(optimizer, loss='mse',metrics=['acc'])
model.fit(df.drop(columns=['label']).values, df['label'].values,epochs=10000,batch_size=1,verbose=0)

In [13]:
print(model.predict(df.drop(columns=['label'])))
print(df['label'])
print(model.evaluate(df.drop(columns=['label']).values, df['label'].values))

[[0.99583673]
 [0.79487395]
 [0.7948742 ]
 [0.01008892]
 [0.00938782]
 [0.00945082]
 [0.9864476 ]
 [0.01015583]
 [0.79487395]
 [0.00248602]
 [0.0099088 ]
 [0.79487395]
 [0.00962397]
 [0.9916209 ]
 [0.99888587]
 [0.7948827 ]]
8     1.0
13    1.0
7     1.0
6     0.0
12    0.0
9     0.0
2     1.0
3     0.0
14    1.0
0     0.0
5     0.0
11    1.0
10    0.0
1     1.0
4     1.0
15    0.0
Name: label, dtype: float64
16/16 [==============================] - 0s 2ms/step
[0.2146482765674591, 0.9375]


In [11]:
input = Input([4,])
d = Dense(4,activation='sigmoid')(input)
o = Dense(1,activation='sigmoid')(d)
optimizer = optimizers.SGD(lr=1e-2)
model = Model(inputs=input,outputs=o)
model.compile(optimizer, loss='mse',metrics=['acc'])
model.fit(df.drop(columns=['label']).values, df['label'].values,epochs=10000,batch_size=1,verbose=0)

print(model.predict(df.drop(columns=['label'])))
print(df['label'])
print(model.evaluate(df.drop(columns=['label']).values, df['label'].values))

[[0.50125045]
 [0.50296843]
 [0.49784622]
 [0.496549  ]
 [0.493301  ]
 [0.5035757 ]
 [0.4969105 ]
 [0.50508595]
 [0.4969819 ]
 [0.50039494]
 [0.49927974]
 [0.5060712 ]
 [0.49783084]
 [0.5014043 ]
 [0.4977909 ]
 [0.5022045 ]]
11    1
9     0
7     1
6     0
4     1
8     1
3     0
15    0
5     0
12    0
1     1
14    1
2     1
13    1
0     0
10    0
Name: label, dtype: int32
16/16 [==============================] - 0s 1ms/step
[0.24990685284137726, 0.5]


"""
from torch import optim
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(4,1)
        self.fc2 = nn.Linear(1,1)
        # self.fc3 = nn.Linear(200, 10)
    def forward(self, x):
        x = F.sigmoid(self.fc1(x))
        x = F.sigmoid(self.fc2(x))
        return x
net = Net()
optimizer = optim.SGD(net.parameters(), lr=0.05, momentum=0.9)
criterion = nn.MSELoss()
for i in range(100):
    for ii in range(len(df.index)):
        data = df.iloc[ii]
        optimizer.zero_grad()
        actual_out = net(data.drop(columns=['label']).values)
        loss = criterion(actual_out, data['label'].values)
        loss.backward()
        optimizer.step()
        print(loss.data[0])
"""

In [3]:
from keras.layers import Dense, Input
from keras.models import Model
from keras import optimizers
import os
# try different dimensionality
result = []
for i in range(1,7,1):
    dg = dataGenerator.ParityDataGenerator(i)
    df = dg.generate_data()
    df = df.sample(frac=1).astype(np.float64)

    input = Input([i,])
    d = Dense(4,activation='sigmoid')(input)
    o = Dense(1,activation='sigmoid')(d)
    optimizer = optimizers.Adam(lr=5e-2)
    model = Model(inputs=input,outputs=o)
    model.compile(optimizer, loss='mse',metrics=['acc'])
    model.fit(df.drop(columns=['label']).values, df['label'].values,epochs=100,batch_size=1,verbose=0)
    result.append(model.evaluate(df.drop(columns=['label']).values, df['label'].values))

Using TensorFlow backend.
C:\Users\rolo_\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\rolo_\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\rolo_\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\rolo_\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning:


Epoch 1/100
2/2 [==============================] - 0s 136ms/step - loss: 0.2604 - acc: 0.5000
Epoch 2/100
2/2 [==============================] - 0s 3ms/step - loss: 0.2321 - acc: 0.5000
Epoch 3/100
2/2 [==============================] - 0s 4ms/step - loss: 0.2175 - acc: 0.5000
Epoch 4/100
2/2 [==============================] - 0s 3ms/step - loss: 0.2006 - acc: 1.0000
Epoch 5/100
2/2 [==============================] - 0s 4ms/step - loss: 0.1941 - acc: 1.0000
Epoch 6/100
2/2 [==============================] - 0s 5ms/step - loss: 0.1879 - acc: 1.0000
Epoch 7/100
2/2 [==============================] - 0s 3ms/step - loss: 0.1874 - acc: 1.0000
Epoch 8/100
2/2 [==============================] - 0s 4ms/step - loss: 0.1808 - acc: 1.0000
Epoch 9/100
2/2 [==============================] - 0s 5ms/step - loss: 0.1724 - acc: 1.0000
Epoch 10/100
2/2 [==============================] - 0s 4ms/step - loss: 0.1671 - acc: 1.0000
Epoch 11/100
2/2 [==============================] - 0s 3ms/step - loss: 0.16

In [4]:
print(result)

[[0.004912564530968666, 1.0], [0.0604325607419014, 1.0], [0.24976664781570435, 0.5], [0.2258147895336151, 0.5625], [0.2501893937587738, 0.5], [0.24878285080194473, 0.515625]]
